### PR TITLE
fix: tasks list has old wrong items and add switch for auto download torrent

### LINKED ISSUE #440: 希望取消自动开始种子文件
**错误描述**
清楚简洁地描述错误，方便我们复现之后处理。

**如何重现**
重现步骤，如：
1. 点击新建任务按钮
2. 黏贴链接（如链接不涉及到隐私和版权问题，请顺便提供）
3. 点击提交
4. 发现报错

**预期的行为**
试图批量下载种子文件，预期是只下载下来种子文件
但是motrix下完后会自动添加种子。

**截图**
请添加屏幕截图以帮助解释你的问题：
打开应用菜单中的「帮助」——「开发者工具」—— 切换到 console，然后**完整**截图。

**运行环境**
 - 操作系统类型： [如 macOS, Windows, Linux]
 - 具体版本： [如 macOS 10.14.2, Windows 10, Ubuntu 18.04]
 - Motrix 版本： [如 v1.1.3, v1.1.0]
 - 安装包类型：[如 dmg, AppImage]

**更多信息**
补充有关该问题的其他信息。

### LINKED ISSUE #934: 请增加一个选项来开关【种子自动下载】的功能
**请描述一下你的新功能请求是否与已知问题有关？**
当前下载完一个torrent文件，会自动开始种子下载。#440
我现在用motrix接管了chrome的所有下载，导致我下载的所有torrent文件都会自动开始，这一点很不好 - 因为我有的种子文件是从pt站里来的，我不希望他被这个软件自动开始。

**描述你想要的解决方案**
在设置里面增加一个开关来控制这个功能。

**描述你考虑过的替代方案**
或者直接不要自动开始。

### LINKED ISSUE #971: 文件列表什么鬼！
点开一个任务的文件列表，发现里面把当前所有任务的文件列表全显示在一起了！这样好吗？

### PR DESCRIPTION
**Pull request by dicarne**
## Description
Tasks list in task detail has wrong items when user switch between different task. I remove old items which shouldn't appear in new list.
Add a switch for auto download magnet link and torrent. Users can choose whether to automatically start downloading all the files in the torrent or whether to download only the torrent file itself.

## Related Issues
Fixes #971
Close #934
Close #440

### Checklist:

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Have you linted your code locally prior to submission?
* [x] Have you successfully ran app with your changes locally?

### CODE REVIEW

File: src/renderer/components/TaskDetail/Index.vue [hunk 1]
```diff
@@ -168,7 +168,7 @@
           }
         })
         merge(cached.files, result)
-
+        cached.files.splice(result.length, cached.files.length - result.length)
```
Comment (agalwood) [inline src/renderer/components/TaskDetail/Index.vue:171]: Remove this line, and add follow codes before `methods`

```javascript
watch: {
  gid () {
    cached.files = []
  }
},
```

File: src/renderer/utils/task.js [hunk 2]
```diff
@@ -16,7 +16,9 @@ export const initTaskForm = state => {
     engineMaxConnectionPerServer,
     maxConnectionPerServer,
     newTaskShowDownloading,
-    split
+    split,
+    followTorrent,
```
Comment (agalwood) [inline src/renderer/utils/task.js:20]: Please sort the keys alphabetically

File: src/renderer/utils/task.js [hunk 3]
```diff
@@ -32,6 +34,8 @@ export const initTaskForm = state => {
     torrent: '',
     uris: addTaskUrl,
     userAgent: '',
+    notFollowMetalink: followMetalink,
```
Comment (agalwood) [inline src/renderer/utils/task.js:37]: Please sort the keys alphabetically

**Review by agalwood — CHANGES_REQUESTED** [review]
You need add `follow-torrent` and `follow-metalink` default value before `'listen-port'` in `ConfigManager.initSystemConfig()`

https://github.com/agalwood/Motrix/blob/509c79989b1b2d48cc43d4fa216e37347fea4b7b/src/main/core/ConfigManager.js#L62
